// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./SimpleNFT.sol";
import "./SimpleNFTHTLC.sol";
import "./SimpleHTLC.sol"; // your COMPLETED Part A contract
import "@openzeppelin/contracts@5.4.0/token/ERC721/IERC721Receiver.sol";

/**
 * Auto-grader for Question 2, SimpleNFTHTLC. Students do not edit this file.
 *
 * Prerequisite: complete Part A in SimpleHTLC.sol and pass its checker first.
 * All five Question 2 files are already together in this folder; the final
 * scenario uses SimpleHTLC and SimpleNFTHTLC for a full atomic sale.
 * In a real exchange, the two contracts are on two different chains.
 *
 * How to run:
 *   1. Answer Q1-Q8 in SimpleNFTHTLC.sol and compile all files.
 *   2. Deploy `SimpleNFTHTLCChecker` (no constructor arguments).
 *   3. Put `1` in the VALUE field (unit: wei) and call `runAllTests`.
 *      - If the transaction reverts, the reason names the question to fix.
 *   4. Call `isSolved` → must return true.
 */

/// Plays the roles of Bob (the buyer) and of a nosy stranger.
contract Participant is IERC721Receiver {
    receive() external payable {}

    function onERC721Received(address, address, uint256, bytes memory) public pure returns (bytes4) {
        return this.onERC721Received.selector;
    }

    function tryWithdraw(SimpleNFTHTLC h, bytes32 secret) external returns (bool ok) {
        try h.withdraw(secret) { return true; } catch { return false; }
    }

    function tryRefund(SimpleNFTHTLC h) external returns (bool ok) {
        try h.refund() { return true; } catch { return false; }
    }

    /// Bob sets up the ETH contract for the seller with the same hash.
    function createEthContract(address seller, bytes32 hashlock, uint256 deadline)
        external payable returns (SimpleHTLC)
    {
        return new SimpleHTLC{value: msg.value}(seller, hashlock, deadline);
    }
}

contract SimpleNFTHTLCChecker is IERC721Receiver {
    bytes32 constant SECRET = "correct horse battery staple";
    bool public solved;

    receive() external payable {}

    function onERC721Received(address, address, uint256, bytes memory) public pure returns (bytes4) {
        return this.onERC721Received.selector;
    }

    function isSolved() external view returns (bool) { return solved; }

    function _isReason(bytes memory err, string memory want) internal pure returns (bool) {
        // Error(string) selector is 0x08c379a0; decode and compare the message.
        if (err.length < 4) return false;
        bytes4 sel;
        assembly { sel := mload(add(err, 0x20)) }
        if (sel != 0x08c379a0) return false;
        assembly {
            // skip 4-byte selector: re-point the bytes array
            err := add(err, 4)
            mstore(err, sub(mload(sub(err, 4)), 4))
        }
        string memory got = abi.decode(err, (string));
        return keccak256(bytes(got)) == keccak256(bytes(want));
    }

    SimpleNFT private nft;
    Participant private bob;
    Participant private stranger;
    bytes32 private hashlock;

    function runAllTests() external payable {
        require(msg.value >= 1, "attach at least 1 wei in the VALUE field");
        nft = new SimpleNFT();
        bob = new Participant();
        stranger = new Participant();
        hashlock = sha256(abi.encodePacked(SECRET));

        _scenario1_liveClaim();
        _scenario2_expiredRefund();
        _scenario3_earlyRefund();
        _scenario4_atomicSale();

        solved = true;
    }

    // --- Scenario 1: live contract — Bob claims the NFT with the secret ------
    function _scenario1_liveClaim() internal {
        uint256 id1 = nft.mint();
        SimpleNFTHTLC live =
            new SimpleNFTHTLC(address(nft), id1, address(bob), hashlock, block.timestamp + 1 hours);
        (bool ok, bytes memory err) =
            address(live).call(abi.encodeCall(SimpleNFTHTLC.withdraw, (SECRET)));
        require(!ok && _isReason(err, "not locked"),
            "Q2: withdraw before lock() must fail on the `locked` guard itself");
        nft.approve(address(live), id1);
        live.lock();
        require(nft.ownerOf(id1) == address(live),
            "Q1: lock() did not actually pull the NFT into the contract");
        require(!stranger.tryWithdraw(live, "wrong guess"),
            "Q5: a wrong secret was accepted");
        // The STRANGER relays the correct secret — the NFT must still reach Bob.
        require(stranger.tryWithdraw(live, SECRET),
            "Q2-Q7: withdraw with the correct secret reverted");
        require(nft.ownerOf(id1) == address(bob),
            "Q7: the NFT did not end up owned by the receiver");
        require(live.settled(), "Q6: the `settled` flag was never set");
        (ok, err) = address(live).call(abi.encodeCall(SimpleNFTHTLC.withdraw, (SECRET)));
        require(!ok && _isReason(err, "already settled"),
            "Q3: a second withdraw must fail on the `settled` guard itself");
    }

    // --- Scenario 2: expired contract — Alice takes the NFT back -------------
    function _scenario2_expiredRefund() internal {
        uint256 id2 = nft.mint();
        SimpleNFTHTLC expired =
            new SimpleNFTHTLC(address(nft), id2, address(bob), hashlock, block.timestamp);
        nft.approve(address(expired), id2);
        expired.lock();
        require(!bob.tryWithdraw(expired, SECRET),
            "Q4: withdraw succeeded after the deadline");
        require(!stranger.tryRefund(expired),
            "refund(): someone other than the sender was allowed to refund");
        expired.refund();
        require(nft.ownerOf(id2) == address(this),
            "refund() did not return the NFT to the sender");
        (bool ok, bytes memory err) = address(expired).call(abi.encodeCall(SimpleNFTHTLC.refund, ()));
        require(!ok && _isReason(err, "already settled"),
            "Q8: a second refund must fail on the `settled` guard itself");
    }

    // --- Scenario 3: refund before the deadline must fail --------------------
    function _scenario3_earlyRefund() internal {
        uint256 id3 = nft.mint();
        SimpleNFTHTLC early =
            new SimpleNFTHTLC(address(nft), id3, address(bob), hashlock, block.timestamp + 1 hours);
        nft.approve(address(early), id3);
        early.lock();
        try early.refund() {
            revert("refund succeeded before the deadline");
        } catch {}
    }

    // --- Scenario 4: THE FULL ATOMIC SALE — two contracts, one secret --------
    // Alice (this checker) sells an NFT to Bob for 1 wei.
    //   NFT contract: Alice's NFT, deadline in 2 hours (LONGER because Bob
    //                 claims second, so his window must outlast Alice's).
    //   ETH contract: Bob's wei, deadline in 1 hour.
    // These represent contracts on two different chains. The checker creates
    // both here only so one test can show the complete sequence.
    function _scenario4_atomicSale() internal {
        uint256 id4 = nft.mint();
        SimpleNFTHTLC nftContract =
            new SimpleNFTHTLC(address(nft), id4, address(bob), hashlock, block.timestamp + 2 hours);
        nft.approve(address(nftContract), id4);
        nftContract.lock();
        SimpleHTLC ethContract =
            bob.createEthContract{value: 1}(address(this), hashlock, block.timestamp + 1 hours);
        // Alice collects her ETH and publishes the secret:
        uint256 balBefore = address(this).balance;
        ethContract.withdraw(SECRET);
        require(address(this).balance == balBefore + 1, "ETH did not reach the seller");
        // Bob reuses the now-public secret in the NFT contract:
        require(bob.tryWithdraw(nftContract, SECRET), "NFT contract rejected the revealed secret");
        require(nft.ownerOf(id4) == address(bob), "atomic sale: Bob did not receive the NFT");
    }
}
