// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts@5.4.0/token/ERC721/ERC721.sol";

/**
 * Given — a minimal open NFT collection. Students do not edit this file.
 *
 * Anyone can mint themselves a fresh NFT; ownership, approvals, and transfers
 * all come from OpenZeppelin's audited ERC-721 implementation (the same one
 * behind the NFT-auction lab's collection).
 */
contract SimpleNFT is ERC721 {
    uint256 public nextId;

    constructor() ERC721("Simple NFT", "SNFT") {}

    function mint() external returns (uint256 tokenId) {
        tokenId = nextId++;
        _safeMint(msg.sender, tokenId);
    }
}
