// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./SimpleHTLC.sol";

/**
 * Auto-grader for Question 2, Part A. Students do not edit this file.
 *
 * How to run (see README.md for screenshots-level detail):
 *   1. Finish the TODOs in SimpleHTLC.sol and compile BOTH files.
 *   2. Deploy `SimpleHTLCChecker` (no constructor arguments).
 *   3. Put `3` in the VALUE field, unit `wei`, and call `runAllTests`.
 *      - If the transaction reverts, the revert reason names the TODO to fix.
 *   4. Call `isSolved` → must return true.
 */

/// Plays the roles of Bob and of a nosy stranger. Can receive ETH.
contract Actor {
    receive() external payable {}

    function tryWithdraw(SimpleHTLC h, bytes32 secret) external returns (bool ok) {
        try h.withdraw(secret) { return true; } catch { return false; }
    }

    function tryRefund(SimpleHTLC h) external returns (bool ok) {
        try h.refund() { return true; } catch { return false; }
    }
}

contract SimpleHTLCChecker {
    bytes32 constant SECRET = "correct horse battery staple";
    bool public solved;

    receive() external payable {}

    function isSolved() external view returns (bool) { return solved; }

    function runAllTests() external payable {
        require(msg.value >= 3, "attach at least 3 wei in the VALUE field");
        Actor bob = new Actor();
        Actor stranger = new Actor();
        bytes32 hashlock = sha256(abi.encodePacked(SECRET));

        // --- Scenario 1: live contract — Bob claims with the secret ---------
        SimpleHTLC live =
            new SimpleHTLC{value: 1}(address(bob), hashlock, block.timestamp + 1 hours);
        require(live.sender() == address(this),
            "TODO 1: `sender` should be whoever deployed and funded the contract");
        require(!stranger.tryWithdraw(live, "wrong guess"),
            "TODO 4: a wrong secret was accepted");
        // The STRANGER relays the correct secret — the money must still reach Bob.
        uint256 bobBefore = address(bob).balance;
        require(stranger.tryWithdraw(live, SECRET),
            "TODO 2-6: withdraw with the correct secret reverted");
        require(address(bob).balance == bobBefore + 1,
            "TODO 6: the ETH did not reach the chosen receiver");
        require(live.settled(), "TODO 5: the `settled` flag was never set");
        require(!stranger.tryWithdraw(live, SECRET),
            "TODO 2: the same deposit was paid out twice");

        // --- Scenario 2: expired contract — Alice takes her money back ------
        SimpleHTLC expired =
            new SimpleHTLC{value: 1}(address(bob), hashlock, block.timestamp);
        require(!bob.tryWithdraw(expired, SECRET),
            "TODO 3: withdraw succeeded after the deadline");
        require(!bob.tryRefund(expired),
            "refund(): someone other than the sender was allowed to refund");
        uint256 meBefore = address(this).balance;
        expired.refund();
        require(address(this).balance == meBefore + 1,
            "refund() did not return the deposit to the sender");
        try expired.refund() {
            revert("TODO 7: a settled contract accepted a second refund");
        } catch {}

        // --- Scenario 3: refund before the deadline must fail ---------------
        SimpleHTLC early =
            new SimpleHTLC{value: 1}(address(bob), hashlock, block.timestamp + 1 hours);
        try early.refund() {
            revert("refund succeeded before the deadline");
        } catch {}

        solved = true;
    }
}
